baseURL = "http://example.org/"
languageCode = "en-us"
title = "Pedro Hung - Portfolio"
theme = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name = "Home"
url = ""
weight = 1
[[menu.nav]]
name = "About"
url = "about"
weight = 3
[[menu.nav]]
name = "Portfolio"
url = "portfolio"
weight = 2
[[menu.nav]]
name = "Get in touch"
url = "contact"
weight = 4

# Site Params
[params]
logo = "images/logo.png"
logo_footer = "images/logo-footer.png"
favicon_icon = "images/favicon.png"
favicon_shortcut_icon = "images/favicon.png"
custom_stylesheets = []                      # [ "scss/my_1.scss", "scss/my_2.scss" ]
dateFormat = "26 FEB 1994"
# Meta data
description = "Pedro Hung Portfolio"
author = "Pedro Hung"
# Google Analitycs
googleAnalitycsID = "Your ID"
# We're using formspree.io for form handling, paste your formspree url below
fabform = "https://fabform.io/f/USAg2Jl"

# Contact Form
[params.contactForm]
placeholder_first_name = "First Name"
placeholder_last_name = "Last Name"
placeholder_email = "Email"
placeholder_project_type = "Project Type"
placeholder_about_the_project = "About the Project"
send_message = "Send Message"

[[params.contactForm.projectType]]
value = "gd"
title = "Graphics Design"
[[params.contactForm.projectType]]
value = "wd"
title = "Web Design"

# Navbar Action Button
[params.navAction]
status = true
name = "Get in touch"
url = "contact"


# Banner Section
[params.portfolio]
enable = true
title = "MY WORK"
subtitle = "Crafting experiences and seeking to make the complex clear & beautiful."
view_project = "view project"
more_works = "MORE WORKS"
